feat(plugin): move plugin to extensions repo
openebs/mayastor-extensions pull request #65
Opened 2022-11-25 06:50 UTC by sinhaashish

Signed-off-by: sinhaashish <ashi.sinha.87@gmail.com>

It was asked to separate  the code for moving kubectl plugin to extions from the upgrade code . Refer https://github.com/openebs/mayastor-extensions/pull/63#pullrequestreview-1192893035

So i have created a PR to move plugin to extensions repo.

2022-11-25 06:51 UTC, sinhaashish commented
bors try

2022-11-25 07:04 UTC, niladrih reviewed
Added few comments.

2022-11-25 07:04 UTC, niladrih commented on Cargo.toml
>      "operators",
The plugin crate needs to be included in this list.

2022-11-25 07:04 UTC, niladrih commented on k8s/plugin/Cargo.toml
> +rest-plugin = { path = "../../control-plane/plugin", default-features = false }
Is this path to the rest-plugin correct? Maybe it should be ../../dependencies/control-plane/plugin

2022-11-25 07:20 UTC, sinhaashish commented
bors try

2022-11-25 07:38 UTC, niladrih commented
Should we also move supportability and kube-proxy to this repo?

2022-11-25 07:42 UTC, sinhaashish commented
> Should we also move supportability and kube-proxy to this repo?

For now , lets have plugin so that the upgrade operator Pr can be evaluated. This can be taken in another PR , upon discussion

2022-11-25 07:43 UTC, niladrih approved these changes

2022-11-25 08:05 UTC, Abhinandan-Purkait approved these changes

2022-11-25 09:27 UTC, sinhaashish commented
bors merge

2022-11-25 12:47 UTC, niladrih requested changes
This also requires build changes in
- https://github.com/openebs/mayastor-extensions/blob/HEAD/nix/pkgs/extensions/default.nix
- https://github.com/openebs/mayastor-extensions/blob/HEAD/nix/pkgs/extensions/cargo-project.nix

you can find the required changes in openebs/mayastor-control-plane's nix files

2022-11-25 17:56 UTC, sinhaashish commented
bors merge

2022-11-25 17:57 UTC, sinhaashish commented
bors try

2022-11-25 17:59 UTC, niladrih approved these changes

2022-11-25 18:01 UTC, tiagolobocastro reviewed
We're missing something like this:
https://github.com/openebs/mayastor-control-plane/blob/develop/nix/pkgs/utils/default.nix
and adding default binary in DEFAULT_BINARIES (./scripts/release.sh)

2022-11-25 18:04 UTC, niladrih requested changes
What Tiago said...

2022-11-29 04:47 UTC, sinhaashish commented
bors try

2022-11-29 04:51 UTC, sinhaashish commented
> What Tiago said...

addressed the review comment. PTAL @tiagolobocastro @niladrih 
Thanks for the help @tiagolobocastro

2022-11-29 08:35 UTC, niladrih approved these changes

2022-11-29 10:07 UTC, tiagolobocastro approved these changes

2022-11-29 11:38 UTC, sinhaashish commented
bors merge

2022-11-29 11:43 UTC, merged