chore: merge develop into release/2.0
openebs/mayastor-extensions pull request #90
Opened 2023-01-13 18:33 UTC by tiagolobocastro

2023-01-13 19:31 UTC, abhilashshetty04 approved these changes

2023-01-14 17:05 UTC, Abhinandan-Purkait approved these changes

2023-01-14 17:21 UTC, avishnu approved these changes
Lgtm

2023-01-16 09:24 UTC, pchandra19 requested changes

2023-01-16 09:24 UTC, pchandra19 commented on chart/README.md.tmpl
> +$ helm repo add openebs https://openebs.github.io/mayastor-charts/
Should be changed to mayastor-extensions.

2023-01-16 11:00 UTC, pchandra19 approved these changes

2023-01-16 12:35 UTC, tiagolobocastro commented
bors merge

2023-01-16 12:39 UTC, merged